name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build C# Code
      run:  dotnet build
      
    - name: TypeScript Code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build
        
    - name: C# Test
      run:  dotnet test
      
    - name: Run TypeScript Tests
      run:  npm t
      
    - name: Run linting of TypeScript 
      run: npm run lint
    
      
